### Post (get)[empty]://///////////////////////////////////post///////////////////

GET http://localhost:3000/Post
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQ1Njg3YTEyZjNlYTdkNTcxZTU4YTgiLCJpYXQiOjE3MTU4MjQ3NjQsImV4cCI6MTcxNTgyNDc2OX0.fzNro9wK8Jpgypmu5dK6Uum5Ckl4Nvsn8-UFFPemuqM

### Post (get)[/:id]:

GET http://localhost:3000/Post/66070b482303c501940b75c7


### Post (get)[?]:

GET http://localhost:3000/Post?sender=Aaa


### Post (Post)[schema obj]:

Post http://localhost:3000/Post
content-type: application/json

{
    "message": "hasfasfuwu ",
    "sender": "Alix"
}

### Post (put)[/:id]:

put http://localhost:3000/Post/66070b482303c501940b75cd
content-type: application/json

{
    "message": "hsdgm aasfasfix "

}

### Post (delete)[/:id]:

delete http://localhost:3000/Post/66070b482303c501940b75c7

### Student (get)[]://///////////////////////////////////student//////////////////  

GET http://localhost:3000/Student     
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQ1Njg3YTEyZjNlYTdkNTcxZTU4YTgiLCJpYXQiOjE3MTU4MjQ5MTUsImV4cCI6MTcxNTgyNzkxNX0.jSCVtIAMKaNUU59vXvHDhjiR935wu_mltJB4SYyswAo

### Student (get)[/:id]:

GET http://localhost:3000/Student/217142406

### Student (get)[?]: 
GET http://localhost:3000/Student?name=Alex

### Student (post)[schema obj]:

POST http://localhost:3000/Student
content-type: application/json

{
    "name": "Alax",
    "_id": "117442406",
    "age": 32
}


### Student (put)[/:id]:

PUT http://localhost:3000/Student/217142406
content-type: application/json

{
    "name": "bobsasfon",
    "_id": "317142436",
    "age": 122
}

### Student (delete)[/:id]:

delete http://localhost:3000/Student/317142436


### Item (get)[empty]://///////////////////////////////////item//////////////////

GET http://localhost:3000/Item

### Item (get)[/:id]:

GET http://localhost:3000/Item/660049079851128e1c76f19f

### Item (get)[?]: 
GET http://localhost:3000/Item?name=ball


### Item (Post)[schema obj]:

Post http://localhost:3000/Item
content-type: application/json

{
    "name": "chair"
}

### Item (put)[/:id]:

put http://localhost:3000/Item/6601c76f19
content-type: application/json

{
    "name": "updated-xD"
}

### Item (delete)[/:id]:

delete http://localhost:3000/Item/660049079851128e1c76f19f

### User (post)[/:register]://///////////////////////////////////User//////////////////  

post http://localhost:3000/Auth/register
content-type: application/json

{
    "_id": "1",
    "name": "1",
    "email": "1",
    "password": "1"
}

###      User (post)[/:login]

post http://localhost:3000/Auth/login 
content-type: application/json

{
    "email": "asax@mail.com",
    "password": "123456"
}

###        User (post)[/:logout]

get http://localhost:3000/Auth/logout
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIzMTc0MTQ1MDYiLCJpYXQiOjE3MTYxNzI4MDgsImV4cCI6MTcxNjE3NTgwOH0.jPye0CqA8ZFRj3lOrGhv_mR-jc_68LqOjw-yBeSvQKI

###

get http://localhost:3000/Auth/refresh
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjBlYTFhZWEwZTljZDFjNDljMzlmMDkiLCJzYWx0IjowLjkxMDQwNzMzNzI5ODA0NDgsImlhdCI6MTcxMjI0MzIwNH0.u_vhirMo0XnS2aKJz7W4y6_j7cw6pdj6gZmsFnPtA7Q


###

GET http://localhost:3000/User

###

GET http://localhost:3000/User/163433